# Generated by Django 4.1.7 on 2023-02-23 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('serial_number', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('manufacturer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_airport_icao', models.CharField(max_length=4)),
                ('depart_at', models.DateTimeField()),
                ('arrival_airport_icao', models.CharField(max_length=4)),
                ('arrive_at', models.DateTimeField()),
                (
                    'aircraft',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='api.aircraft'
                    ),
                ),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
